### ISSUE TITLE
Create Enemy Variations

### ISSUE THREAD

**Issue by jjh9397** [jjh9397/minirogue#18]
- [x] create parameters to allow tuning and randomization of stats such as projectile speed and number
- [x] create variations in rotation
- [x] create variations in movement parameters
- [ ] create more patterns

**Comment by andyh4050** [comment]
Types of patterns:
Melee enemy, does damage through contact and chases player character
Spiral enemy, fires slow projectiles in a circling spiral
Shotgun enemy, fires several projectiles in a cone at the player
Sniper enemy, follow the player with a laser targeter, then "locks on" and fires a very fast projectile at that location
(?) Grenade enemy, lobs physics based projectiles at the player
(?) Explosive enemy, fires projectiles that split into more projectiles upon contact with a surface
